# Changes here will be overwritten by Copier
_commit: 8eb759a
_src_path: https://github.com/jetxeberria/galtzagorri.git
github_or_gitlab: GitHub
project_description: A new project created with Copier
project_name: etsai
